/// @file
/// @copyright  Copyright 2022-2026 Timothy Place. All rights reserved.
/// @license    Use of this source code is governed by the MIT License found in the License.md file.

#pragma once

// The core (core/include/tap/python/) includes CPython, which insists on preceding system headers.
#include "tap/python/processor.h"
#include "tap/python/runtime.h"
#include "tap/python/value.h"
#include "tap/python/worker.h"

// c74_min.h must be the FIRST min header in the translation unit: it defines
// C74_MIN_WITH_IMPLEMENTATION so the min wrapper's out-of-line statics get
// emitted here. If c74_min_api.h sneaks in first (e.g. via our helper headers),
// the include guards swallow those definitions and the external fails to link.
#include <algorithm>
#include <atomic>
#include <cstring>
#include <memory>
#include <string>
#include <unordered_map>
#include <vector>

#include "c74_min.h"
#if defined(__APPLE__)
#include <mach/mach.h>
#include <mach/mach_time.h>
#include <mach/thread_policy.h>
#include <pthread.h>
#endif
#include "tap.python_tilde_attribute.h"
#include "tap.python_tilde_cglue.h"
#include "tap.python_tilde_filewatch.h"
#include "tap.python_tilde_message.h"
#include "tap.python_tilde_package.h"

using namespace c74::min;
namespace runtime = tap::python;

class python : public object<python>, public vector_operator<> {
  public:
    // The reference page (docs/tap.python~.maxref.xml) is generated by min from these descriptions
    // whenever the external is newer than it, so this is where the documentation lives. Write no
    // angle brackets: min copies the text into the XML unescaped.
    MIN_DESCRIPTION{"Process audio with a Python class. The argument names a file in the package's python folder, "
                    "which must define a class of the same name. The class's type-annotated public fields become "
                    "attributes (int, float, bool and str; Optional allowed), and its public methods become "
                    "messages called according to their signatures, with methods named int, float, symbol and "
                    "bang answering those standard messages. Its process() method runs on the signal: once per "
                    "signal vector when annotated with numpy arrays, or once per sample when annotated with "
                    "float; its parameters are the object's signal inlets, and its return hint its outlets "
                    "(a tuple of values for more than one). An optional prepare(sample_rate, vector_size) "
                    "method receives the audio settings "
                    "before audio starts and whenever they change. With @mode worker, process() runs on a thread of "
                    "its own, @latency milliseconds behind the audio, so that nothing else Python does can hold "
                    "the audio up. The file is watched and reloaded when saved, "
                    "keeping attribute values; a save that changes process()'s inputs or outputs changes the "
                    "inlets and outlets to match, keeping the patch cords of those that stay. Errors are "
                    "printed to the Max console and never take Max down."};
    MIN_TAGS{"programming"};
    MIN_AUTHOR{"Tim Place"};
    MIN_RELATED{"js, node.script"};

    // The first inlet and outlet; the constructor adds as many more as the class's process()
    // declares, and a reload changes them to match (plan 2.4).
    inlet<>  m_inlet{this, "(signal) the first input to the Python process() method, and messages"};
    outlet<> m_outlet_main{this, "(signal) the first output returned from the Python process() method", "signal"};

    argument<symbol> m_source_arg{
        this, "source",
        "Python class file. The name of a .py file in the package's python folder, without the "
        "extension, which must define a class of the same name; it must be a valid Python "
        "identifier. Without an argument, python/default.py is loaded."};

    // Sent on every save of the class file (by the watch the constructor starts — see
    // tap.python_tilde_filewatch.h), and by a patcher to force a reload.
    message<> m_filechanged{this, "filechanged",
                            "Reload the Python file. The object's file watcher sends it when the file is saved; "
                            "send it yourself to force a reload.",
                            MIN_FUNCTION {
                                // not announced here: the processor that runs the changed file says
                                // so, once, however many objects share it (plan 6.7)
                                try {
                                    update_source();
                                }
                                catch (const std::exception& e) {
                                    cerr << "reload failed: " << e.what() << endl;
                                }
                                return {};
                            }};

    // What went wrong on the audio thread (an exception in process(), a non-numeric or non-finite
    // result) is reported from here, on Max's main thread: the core calls report_ready on the audio
    // thread, which only sets this qelem.
    queue<> m_reports{this,
                      MIN_FUNCTION {
                          if (m_processor) {
                              try {
                                  m_processor->flush_reports();
                                  m_worker->flush_reports();
                              }
                              catch (const std::exception& e) {
                                  cerr << "reporting failed: " << e.what() << endl;
                              }
                          }
                          return {};
                      }};

    // Called by min when the signal chain compiles, with the sample rate and the maximum vector size:
    // passed on to the class's prepare(), if it has one. (min finds it by the member name "dspsetup";
    // its m_dspsetup alternative is detected but then called as dspsetup, so it does not compile.)
    message<> dspsetup{this, "dspsetup",
                       MIN_FUNCTION {
                           if (m_processor) {
                               const auto sample_rate = static_cast<double>(args[0]);
                               const auto vector_size = static_cast<std::size_t>(static_cast<long>(args[1]));
                               try {
                                   m_processor->prepare(sample_rate, vector_size);
                               }
                               catch (const std::exception& e) {
                                   cerr << "prepare failed: " << e.what() << endl;
                               }
                               set_up_worker(sample_rate, vector_size);
                           }
                           return {};
                       }};

    // Worker mode (plan 2.5): where process() runs, and how far behind. Both take effect when the
    // signal chain compiles; setting either rebuilds it, so that is at once while audio runs.
    attribute<symbol> m_mode{this,
                             "mode",
                             "direct",
                             description{"Where process() runs: direct, on the audio thread, with no latency; or "
                                         "worker, on a thread of its own, about latency milliseconds behind, so that "
                                         "nothing Python does elsewhere (a reload, a message, a garbage "
                                         "collection) can hold up the audio."},
                             range{"direct", "worker"},
                             c74::min::setter{MIN_FUNCTION {
                                 const bool worker = !args.empty() && args[0] == symbol("worker");
                                 rebuild_signal_chain();
                                 return {symbol(worker ? "worker" : "direct")};
                             }}};
    attribute<double> m_latency{this,
                                "latency",
                                runtime::worker::k_default_latency_ms,
                                description{"The latency in worker mode, in milliseconds (0 to 1000), rounded up "
                                            "to whole signal vectors, at least one. It must be longer than Max's I/O "
                                            "vector, which Max computes all at once: what is left over is the time "
                                            "Python has to keep up. More absorbs longer pauses, at the cost of "
                                            "delay."},
                                range{0.0, 1000.0},
                                c74::min::setter{MIN_FUNCTION {
                                    rebuild_signal_chain();
                                    return {std::clamp(static_cast<double>(args[0]), 0.0, 1000.0)};
                                }}};
    attribute<int>    m_latencysamples{this, "latencysamples", 0,
                                    description{"The delay worker mode adds, in samples (latency rounded up to "
                                                   "whole signal vectors), for aligning other signal paths; 0 in "
                                                   "direct mode or with audio off."},
                                    readonly{true}};

    python(const atoms& args = {}) {
        if (maxobj() == NULL) {
            return; // this occurs during dummy construction
        }

        const auto package = runtime::package_root();
        m_scripts_dir      = package / "python";
#ifdef TAP_PYTHON_HOME
        // Linux development builds embed a system CPython instead of a support/ runtime
        // (see this object's CMakeLists.txt)
        const std::filesystem::path home{TAP_PYTHON_HOME};
#else
        const auto home = runtime::runtime_home(package); // support/, or support/<platform> (plan 4.8)
#endif

        if (!std::filesystem::exists(home)) {
            cerr << "No Python runtime found at " << home.string()
                 << " — run scripts/install-runtime from the package root to install it." << endl;
            return;
        }

        if (std::string error; !runtime::runtime_library_loadable(home, error)) {
            cerr << error << endl;
            return;
        }

        const auto status = runtime::initialize({home, m_scripts_dir, console_line});
        if (!status.ok) {
            cerr << "failed to start Python from '" << home.string() << "': " << status.error
                 << " (run scripts/install-runtime to install the runtime)" << endl;
            return;
        }

        if (args.empty()) {
            m_python_source = "default";
        }
        else {
            // the class file's name: one symbol, read as it is (anything else, as text, is not a
            // valid name, and the core says so)
            m_python_source = args.size() == 1 && c74::max::atom_gettype(&args[0]) == c74::max::A_SYM
                                  ? std::string{c74::max::atom_getsym(&args[0])->s_name}
                                  : to_string(args);
        }

        const auto object_log = [this](const runtime::log_level level, const std::string_view text) {
            if (level == runtime::log_level::error) {
                cerr << std::string{text} << endl;
            }
            else {
                cout << std::string{text} << endl;
            }
        };
        m_processor = std::make_unique<runtime::processor>(
            m_python_source, object_log, reserved_messages(), [this] { m_reports.set(); },
            [this](const std::string& name) { return answered_by_max(name); });
        m_worker = std::make_unique<runtime::worker>(
            *m_processor, object_log, [this] { m_reports.set(); }, audio_thread_scheduling);

        update_source();
        create_ports(); // before min makes the Max inlets and outlets from its lists, after this

        // watch the source file for changes (delivered as our 'filechanged' message) — only a plain
        // file name: the core refuses anything else (e.g. "../x"), and so must the watcher
        if (m_python_source.find_first_of("/\\.:") != std::string::npos) {
            return;
        }
        const auto watched_file = m_scripts_dir / (m_python_source + ".py");
        char       filename[c74::max::MAX_PATH_CHARS]{};
        std::strncpy(filename, watched_file.string().c_str(), c74::max::MAX_PATH_CHARS - 1);
        short              path_id{};
        c74::max::t_fourcc filetype{};
        if (c74::max::locatefile_extended(filename, &path_id, &filetype, nullptr, 0) == 0) {
            // not maxobj() itself: see tap.python_tilde_filewatch.h
            m_file_watch = std::make_unique<runtime::file_watch>(maxobj(), path_id, filename);
        }
        else {
            cerr << "Unable to watch " << watched_file.string() << " for changes." << endl;
        }
    }

    ~python() {
        m_file_watch.reset();
        m_use_worker = false;
        m_worker.reset();    // joins the worker thread, before the processor it runs goes
        m_processor.reset(); // releases the Python objects under the GIL
    }

    /// (Re)import the user's module, instantiate its class, and rebuild the Max
    /// attributes and messages from the class's type hints. Called from the Max
    /// main thread (constructor and file watcher).
    void update_source() {
        if (!m_processor || !m_processor->load()) {
            return; // the processor has reported why, and outputs silence until the next reload
        }
        create_attributes();
        create_messages();
        adapt_ports();
    }

    /// Dispatch a Max message to the bound Python method.
    /// Runs on the Max main or scheduler thread.
    void message_gimme(const symbol name, const long ac, const c74::max::t_atom* av) {
        if (!m_processor || !m_processor->loaded()) {
            return;
        }
        m_processor->call(name.c_str(), to_values(ac, av));
    }

    void attr_set(const symbol& name, const long argc, const c74::max::t_atom* argv) {
        if (!m_processor || !m_processor->loaded()) {
            return;
        }
        if (argc != 1) {
            cerr << "Attributes with more than 1 arg not supported" << endl;
            return;
        }

        auto found = m_python_attributes.find(name.c_str());
        if (found == m_python_attributes.end()) {
            return;
        }

        // the core converts to the field's hinted type (a bool field gets a bool)
        m_processor->set_attribute(name.c_str(), to_values(argc, argv).front());
    }

    void attr_get(const symbol& name, long* argc, c74::max::t_atom** argv) {
        if ((*argc) != 1 || !(*argv)) { // otherwise use memory passed in
            if (*argc && *argv) {
                c74::max::sysmem_freeptr(*argv);
                *argv = NULL;
            }
            *argc = 1;
            *argv = reinterpret_cast<c74::max::t_atom*>(c74::max::sysmem_newptr(sizeof(c74::max::t_atom) * (*argc)));
        }
        c74::max::atom_setfloat(*argv, 0.0); // default in case anything below fails

        if (!m_processor || !m_processor->loaded()) {
            return;
        }

        auto found = m_python_attributes.find(name.c_str());
        if (found == m_python_attributes.end()) {
            return;
        }

        // nothing to read (None, or a value that does not convert): the type's empty value
        const auto type = found->second->value_type();
        if (type == runtime::value_type::integer || type == runtime::value_type::boolean) {
            c74::max::atom_setlong(*argv, 0);
        }
        else if (type == runtime::value_type::symbol) {
            c74::max::atom_setsym(*argv, c74::max::gensym(""));
        }

        const auto result = m_processor->get_attribute(name.c_str(), type);
        if (!result) {
            return;
        }
        if (const auto* i = std::get_if<std::int64_t>(&*result)) {
            c74::max::atom_setlong(*argv, static_cast<c74::max::t_atom_long>(*i));
        }
        else if (const auto* d = std::get_if<double>(&*result)) {
            c74::max::atom_setfloat(*argv, *d);
        }
        else {
            c74::max::atom_setsym(*argv, c74::max::gensym(std::get<std::string>(*result).c_str()));
        }
    }

    /// The audio perform routine: the core calls the Python process() once per sample or per
    /// vector, holding the GIL for the vector, and outputs silence while unbound.
    void operator()(audio_bundle input, audio_bundle output) {
        if (!m_processor) {
            output.clear();
            return;
        }
        try {
            // every channel Max gives: the core matches them to what process() declares (plan 2.4)
            const auto inputs  = static_cast<std::size_t>(input.channel_count());
            const auto outputs = static_cast<std::size_t>(output.channel_count());
            const auto frames  = static_cast<std::size_t>(input.frame_count());
            if (m_use_worker.load(std::memory_order_acquire)) { // never takes the GIL (plan 2.5)
                m_worker->process(input.samples(), inputs, output.samples(), outputs, frames);
            }
            else {
                m_processor->process(input.samples(), inputs, output.samples(), outputs, frames);
            }
        }
        catch (...) { // never let an exception unwind into the audio driver
            output.clear();
        }
    }

    /// The names of the Max messages made for the class's methods (for the tests).
    std::vector<std::string> python_message_names() const {
        std::vector<std::string> names;
        names.reserve(m_python_messages.size());
        for (const auto& element : m_python_messages) {
            names.push_back(element.first);
        }
        std::sort(names.begin(), names.end());
        return names;
    }

  private:
    string                                 m_python_source{};
    std::filesystem::path                  m_scripts_dir{};
    std::unique_ptr<runtime::file_watch>   m_file_watch;
    std::unique_ptr<runtime::processor>    m_processor;
    std::unique_ptr<runtime::worker>       m_worker;       // runs m_processor
    std::atomic<bool>                      m_use_worker{}; // read by the audio thread
    std::vector<std::unique_ptr<inlet<>>>  m_more_inlets;  // after the first
    std::vector<std::unique_ptr<outlet<>>> m_more_outlets; // after the first
    bool                                   m_ports_made{};
    bool                                   m_ports_differ{};
    std::unordered_map<std::string, std::unique_ptr<runtime::python_message>> m_python_messages;
    std::unordered_map<std::string, std::unique_ptr<runtime::python_attr>>    m_python_attributes;

    /// Messages and attributes the Max object handles itself, which a Python method or field must
    /// never replace: min's own class methods, the messages Max sends every object, this object's
    /// file watcher (a Python method named filechanged would silently disable hot reload), and its
    /// own attributes (worker mode's, plan 2.5).
    ///
    /// Above all, every message Max sends with C arguments (plan 8.2, audit A3): a Python method
    /// of such a name would be registered with the A_GIMME trampoline, and Max calling it with a
    /// long or a pointer reads them as a symbol and an atom list — the crash 6.1 found for
    /// filechanged, in its general form. The names are those min treats as A_CANT
    /// (c74_min_message.h, message_type::cant; the MIN_WRAPPER_ADDMETHOD table in
    /// c74_min_object_wrapper.h) plus Max's own dspstate, inputchanged and multichanneloutputs.
    /// Anything the Max class already answers is reserved as well: answered_by_max().
    static std::vector<std::string> reserved_messages() {
        return {"anything",
                "appendtodictionary",
                "assist",
                "dblclick",
                "dictionary",
                "dsp",
                "dsp64",
                "dspsetup",
                "dspstate",
                "edclose",
                "filechanged",
                "fileusage",
                "focusgained",
                "focuslost",
                "getplaystate",
                "getvalueof",
                "inletinfo",
                "inputchanged",
                "jitclass_setup",
                "key",
                "latency",
                "latencysamples",
                "loadbang",
                "maxclass_setup",
                "maxob_setup",
                "mode",
                "mop_setup",
                "mousedoubleclick",
                "mousedown",
                "mousedrag",
                "mousedragdelta",
                "mouseenter",
                "mouseleave",
                "mousemove",
                "mouseup",
                "mousewheel",
                "mt_mousedown",
                "mt_mousedrag",
                "mt_mouseenter",
                "mt_mouseleave",
                "mt_mousemove",
                "mt_mouseup",
                "multichanneloutputs",
                "notify",
                "okclose",
                "oksize",
                "paint",
                "patchlineupdate",
                "preset",
                "savestate",
                "setup",
                "setvalueof",
                "signal"};
    }

    /// Whether the Max object already answers `name` itself — a method its class registered (min's
    /// dsp64, assist, the ones above), which Max would call before anything added for a Python
    /// method, or with C arguments. The messages this object added for the previous incarnation's
    /// Python methods are its own, not Max's: still registered while load() runs, they must not
    /// make the class's methods reserved on a reload. Main thread.
    bool answered_by_max(const std::string& name) {
        if (m_python_messages.find(name) != m_python_messages.end()) {
            return false;
        }
        return c74::max::object_getmethod(maxobj(), c74::max::gensym(name.c_str())) != nullptr;
    }

    /// The worker thread's scheduling (plan 2.5): the real-time class an audio thread has, so that a
    /// busy machine does not hold it off for longer than its latency (measured in Max: an ordinary
    /// thread was late even with 32 vectors of latency). On the worker thread as it starts, with the
    /// vector period in seconds. If the system refuses, the thread keeps ordinary scheduling.
    static void audio_thread_scheduling(const double period) {
#if defined(__APPLE__)
        // Mach's time-constraint policy, in Mach absolute time: the thread runs once a period, needs
        // up to half of it, and must be done within it
        if (period <= 0.0) {
            return;
        }
        mach_timebase_info_data_t timebase{};
        if (mach_timebase_info(&timebase) != KERN_SUCCESS || timebase.numer == 0) {
            return;
        }
        const double                         ticks = period * 1e9 * timebase.denom / timebase.numer;
        thread_time_constraint_policy_data_t policy{};
        policy.period      = static_cast<std::uint32_t>(ticks);
        policy.computation = static_cast<std::uint32_t>(ticks / 2);
        policy.constraint  = static_cast<std::uint32_t>(ticks);
        policy.preemptible = 1;
        thread_policy_set(pthread_mach_thread_np(pthread_self()), THREAD_TIME_CONSTRAINT_POLICY,
                          reinterpret_cast<thread_policy_t>(&policy), THREAD_TIME_CONSTRAINT_POLICY_COUNT);
#elif defined(_WIN32)
        SetThreadPriority(GetCurrentThread(), THREAD_PRIORITY_TIME_CRITICAL);
#else
        (void)period; // Linux development builds: no host runs there
#endif
    }

    /// Python's print() output and tracebacks, for every instance.
    static void console_line(const runtime::log_level level, const std::string_view text) {
        const std::string line{text};
        if (level == runtime::log_level::error) {
            c74::max::object_error(nullptr, "python: %s", line.c_str());
        }
        else {
            c74::max::object_post(nullptr, "python: %s", line.c_str());
        }
    }

    /// Max atoms as core values, keeping each atom's own type (the core coerces to the
    /// hinted type with the same rules as atom_getlong/atom_getfloat/atom_getsym).
    static std::vector<runtime::value> to_values(const long ac, const c74::max::t_atom* av) {
        std::vector<runtime::value> values;
        values.reserve(static_cast<std::size_t>(ac));
        for (long i = 0; i < ac; ++i) {
            const auto* atom = av + i;
            switch (c74::max::atom_gettype(atom)) {
            case c74::max::A_LONG:
                values.emplace_back(static_cast<std::int64_t>(c74::max::atom_getlong(atom)));
                break;
            case c74::max::A_FLOAT:
                values.emplace_back(static_cast<double>(c74::max::atom_getfloat(atom)));
                break;
            default:
                values.emplace_back(std::string{c74::max::atom_getsym(atom)->s_name});
                break;
            }
        }
        return values;
    }

    /// Make the Max attributes match the class's annotated fields: remove the ones the class no
    /// longer has, recreate the ones whose type changed, add the new ones. (The core has already
    /// carried the values of those that stayed over to the new instance.)
    void create_attributes() {
        const auto& current = m_processor->attributes();
        for (auto it = m_python_attributes.begin(); it != m_python_attributes.end();) {
            const auto found = std::find_if(current.begin(), current.end(),
                                            [&](const runtime::attribute_info& a) { return a.name == it->first; });
            if (found == current.end() || found->type != it->second->value_type()) {
                it->second->remove();
                it = m_python_attributes.erase(it);
            }
            else {
                ++it;
            }
        }
        for (const auto& attribute : current) {
            if (m_python_attributes.find(attribute.name) == m_python_attributes.end()) {
                m_python_attributes[attribute.name] =
                    std::make_unique<runtime::python_attr>(maxobj(), attribute.name, attribute.type);
            }
        }
    }

    /// A signal inlet for each input the class's process() declares, named for its parameter, and
    /// an outlet for each output — at least one of each: the first inlet also takes messages.
    /// Constructor only: min makes the Max inlets and outlets from these when it returns.
    void create_ports() {
        describe_ports(m_processor ? std::max<std::size_t>(1, m_processor->input_count()) : 1,
                       m_processor ? m_processor->output_count() : 1);
        m_ports_made = true;
    }

    /// Make the inlets and outlets match what a reloaded class's process() declares, in place:
    /// Max's dynamic inlets and outlets, changed between the box's dynlet_begin and dynlet_end,
    /// keep the patch cords of every inlet and outlet that stays. The signal chain is then marked
    /// broken, so it is rebuilt with the new counts. An object without a box (made by object_new)
    /// keeps its ports and says so, once, until they match again; the core matches the channels: a
    /// missing input reads as silence, an extra output is dropped.
    void adapt_ports() {
        if (!m_ports_made) {
            return;
        }
        const auto inlets  = 1 + m_more_inlets.size();
        const auto outlets = 1 + m_more_outlets.size();
        const auto inputs  = std::max<std::size_t>(1, m_processor->input_count());
        const auto outputs = m_processor->output_count();
        if (inputs == inlets && outputs == outlets) {
            describe_ports(inlets, outlets); // a parameter may have been renamed
            m_ports_differ = false;
            return;
        }

        c74::max::t_object* box{};
        if (c74::max::object_obex_lookup(maxobj(), k_sym__pound_b, &box) != c74::max::MAX_ERR_NONE || !box) {
            if (!m_ports_differ) {
                cout << "process() now has " << inputs << " input(s) and " << outputs << " output(s); this object has "
                     << inlets << " inlet(s) and " << outlets << " outlet(s) — re-create it to change them" << endl;
            }
            describe_ports(inlets, outlets);
            m_ports_differ = true;
            return;
        }

        c74::max::object_method(box, c74::max::gensym("dynlet_begin"));
        c74::max::dsp_resize(reinterpret_cast<c74::max::t_pxobject*>(maxobj()), static_cast<long>(inputs));
        for (auto n = outlets; n > outputs; --n) {
            c74::max::outlet_delete(c74::max::outlet_nth(maxobj(), static_cast<long>(n - 1)));
        }
        for (auto n = outlets; n < outputs; ++n) {
            c74::max::outlet_append(maxobj(), nullptr, c74::max::gensym("signal"));
        }
        describe_ports(inputs, outputs); // min's lists follow Max's before anything can read them
        c74::max::object_method(box, c74::max::gensym("dynlet_end"));
        m_ports_differ = false;

        rebuild_signal_chain();
    }

    /// Have Max rebuild the signal chain this object is in (as it does when patch cords change),
    /// which calls dspsetup again: after its inlets or outlets change, or worker mode's settings.
    void rebuild_signal_chain() {
        if (maxobj() == nullptr) {
            return;
        }
        if (auto* chain = c74::max::dspchain_fromobject(maxobj())) {
            c74::max::dspchain_setbroken(chain);
        }
    }

    /// Start the worker for the chain being compiled — this object's inlets and outlets, the
    /// vector size, @latency — or stop it in direct mode. Main thread, from dspsetup; the old chain
    /// may still be running, which the worker allows for (plan 2.5).
    void set_up_worker(const double sample_rate, const std::size_t vector_size) {
        if (m_mode.get() == symbol("worker")) {
            m_worker->start(1 + m_more_inlets.size(), 1 + m_more_outlets.size(), vector_size,
                            runtime::worker::latency_vectors(m_latency, sample_rate, vector_size), sample_rate);
            m_use_worker.store(true, std::memory_order_release);
        }
        else {
            m_use_worker.store(false, std::memory_order_release);
            m_worker->stop();
        }
        // set directly (not through Max, which refuses to set a readonly attribute), overriding readonly
        m_latencysamples.set({static_cast<int>(m_worker->latency_samples())}, false, true);
    }

    /// min's lists of this object's inlets and outlets, one entry for each the Max object has:
    /// min's dsp64 reads a connection count for each, and its assist the help text, which names
    /// each inlet for its process() parameter. They make no Max inlets or outlets after the
    /// constructor: the Max ones are made by min (at creation) or by adapt_ports().
    void describe_ports(const std::size_t inlet_count, const std::size_t outlet_count) {
        auto& inlet_list = inlets();
        for (const auto& more : m_more_inlets) {
            inlet_list.erase(std::remove(inlet_list.begin(), inlet_list.end(), more.get()), inlet_list.end());
        }
        m_more_inlets.clear();
        const auto& names = m_processor ? m_processor->input_names() : std::vector<std::string>{};
        for (std::size_t i = 1; i < inlet_count; ++i) {
            const auto number = std::to_string(i + 1);
            m_more_inlets.push_back(std::make_unique<inlet<>>(
                this, i < names.size()
                          ? "(signal) " + names[i] + ": input " + number + " to the Python process() method"
                          : "(signal) input " + number + ": not used by the Python process() method"));
        }

        auto& outlet_list = outlets();
        while (1 + m_more_outlets.size() > outlet_count && !m_more_outlets.empty()) {
            const auto* last = m_more_outlets.back().get();
            outlet_list.erase(std::remove(outlet_list.begin(), outlet_list.end(), last), outlet_list.end());
            m_more_outlets.pop_back();
        }
        while (1 + m_more_outlets.size() < outlet_count) {
            const auto number = std::to_string(m_more_outlets.size() + 2);
            m_more_outlets.push_back(std::make_unique<outlet<>>(
                this, "(signal) output " + number + " returned from the Python process() method", "signal"));
        }
    }

    /// Replace the previous incarnation's Max messages with the class's current methods.
    void create_messages() {
        for (auto& element : m_python_messages) {
            c74::max::object_deletemethod(maxobj(), c74::max::gensym(element.first.c_str()));
        }
        m_python_messages.clear();

        for (const auto& message : m_processor->messages()) { // never names an attribute
            m_python_messages[message.name] = std::make_unique<runtime::python_message>(maxobj(), message.name);
        }
    }
};
