#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
# Copyright 2022-2026 Timothy Place.
"""Run tap.python~'s runtime tests inside a real Max (plan 6.1, 6.4).

    python3 runtime-tests/run.py                     # everything: both sessions below
    python3 runtime-tests/run.py --session main      # just the tests with the runtime installed
    python3 runtime-tests/run.py --only reload -v    # the main tests whose names contain "reload"
    python3 runtime-tests/run.py --session soak      # the hour-long soak (plan 6.2), on its own
    python3 runtime-tests/run.py --session perf      # Max's CPU meter under load (plan 6.3)

Needs macOS with Max 9, the external built (cmake --build build), the runtime installed
(scripts/install-runtime.sh), and the package in Max's Packages folder as "PythonTap". It launches
Max itself, drives it over OSC through the max-test harness (the runtime-tests/max-test submodule),
and quits it when done, so do not run it while Max is open. Two sessions:

    without-runtime  support/ is moved aside before Max starts: the object must still load and
                     say what is missing (4.2). support/ is then put back while Max runs, and a
                     new object must still say so — on macOS the weak binding is fixed when the
                     external loads, so a runtime installed later needs a restart (by design).
    main             the patchers in runtime-tests/patchers/, generated by make_patchers.py.
    soak             (only when asked for) an hour of audio, saves every second and a sample-rate
                     change; Max's memory is sampled every minute, and a summary of it, the
                     reloads, Max's DSP CPU and Python's object count goes to logs/soak.summary.
    perf             (only when asked for) Max's own DSP CPU meter with instances of the shipped
                     examples, averaged into logs/perf.json (scripts/update-perf-docs.py --max).

It installs the harness into Packages as max-test (a copy: Max loads extensions only from a real
folder; it stays installed), links runtime-tests/ in as PythonTap-runtime-tests for the run, and
copies the fixtures in runtime-tests/python/ into python/, where tap.python~ looks for class files;
it removes the link and the copies afterwards, and always puts support/ back. Results come from the
harness's SQLite database; the exit status is non-zero if anything failed. See README.md here.
"""

from __future__ import annotations

import argparse
import json
import shutil
import socket
import sqlite3
import struct
import subprocess
import sys
import time
from pathlib import Path

TESTS = Path(__file__).resolve().parent
ROOT = TESTS.parent
HARNESS = TESTS / "max-test"
PATCHERS = TESTS / "patchers"
FIXTURES = TESTS / "python"
LOGS = TESTS / "logs"
SCRIPTS_DIR = ROOT / "python"
SUPPORT = ROOT / "support"
SUPPORT_ASIDE = ROOT / "support.maxtest-aside"
EXTERNAL = ROOT / "externals" / "tap.python~.mxo"
OSCAR = HARNESS / "extensions" / "oscar.mxo"

# Must match misc/max-test-config.json: Max listens on one port and sends to the other.
MAX_LISTENS = 4791
MAX_SENDS = 4792
HOST = "127.0.0.1"

# The harness is installed as a copy (see install_harness); the tests are linked in.
TEST_PACKAGE = "PythonTap-runtime-tests"
HARNESS_STAMP = "INSTALLED-BY-PYTHONTAP.txt"

# The without-runtime patchers are not named *.maxtest.maxpat, so that the harness's own "run
# everything" never picks them up in a session that has a runtime.
WITHOUT_RUNTIME = ["tap.python~.without-runtime.maxpat", "tap.python~.without-runtime-restart.maxpat"]
SOAK = "tap.python~.soak.maxpat"
PERF = "tap.python~.perf.maxpat"
MEMORY_EVERY = 60.0  # seconds between samples of Max's memory during the soak


class RunError(Exception):
    pass


# ---- OSC, just enough for the harness: string and number arguments over UDP -----------------


def _osc_string(text: str) -> bytes:
    data = text.encode()
    return data + b"\0" * (4 - len(data) % 4)


def osc_message(address: str, *args) -> bytes:
    tags = ","
    payload = b""
    for arg in args:
        if isinstance(arg, str):
            tags += "s"
            payload += _osc_string(arg)
        elif isinstance(arg, int):
            tags += "i"
            payload += struct.pack(">i", arg)
        else:
            tags += "f"
            payload += struct.pack(">f", arg)
    return _osc_string(address) + _osc_string(tags) + payload


def _read_osc_string(data: bytes, offset: int) -> tuple[str, int]:
    end = data.index(b"\0", offset)
    return data[offset:end].decode(errors="replace"), (end // 4 + 1) * 4


def parse_osc(data: bytes) -> tuple[str, list]:
    address, offset = _read_osc_string(data, 0)
    if offset >= len(data):
        return address, []
    tags, offset = _read_osc_string(data, offset)
    args = []
    for tag in tags[1:]:
        if tag == "s":
            value, offset = _read_osc_string(data, offset)
        elif tag == "i":
            (value,) = struct.unpack_from(">i", data, offset)
            offset += 4
        elif tag == "f":
            (value,) = struct.unpack_from(">f", data, offset)
            offset += 4
        else:
            break
        args.append(value)
    return address, args


# ---- one Max session --------------------------------------------------------------------------


class MaxSession:
    """A Max launched for testing, and the harness's OSC port inside it."""

    def __init__(self, max_app: Path, name: str, verbose: bool):
        self.name = name
        self.verbose = verbose
        LOGS.mkdir(exist_ok=True)
        self.console_path = LOGS / f"{name}.log"
        self.socket = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        self.socket.bind((HOST, MAX_SENDS))
        self.socket.settimeout(0.25)
        binary = max_app / "Contents" / "MacOS" / "Max"
        self.console = open(self.console_path, "w")
        # oscar mirrors the Max console to standard output
        self.process = subprocess.Popen([str(binary)], stdout=self.console, stderr=subprocess.STDOUT)
        self.db_path = ""
        self.started = time.monotonic()
        self.sample_memory = False
        self.memory: list[tuple[float, int]] = []  # (seconds since launch, resident KB)
        self._next_sample = 0.0

    def _tick(self) -> None:
        if self.sample_memory and time.monotonic() >= self._next_sample:
            self._next_sample = time.monotonic() + MEMORY_EVERY
            result = subprocess.run(["ps", "-o", "rss=", "-p", str(self.process.pid)], capture_output=True, text=True)
            if result.returncode == 0 and result.stdout.strip():
                self.memory.append((time.monotonic() - self.started, int(result.stdout.strip())))

    def send(self, address: str, *args) -> None:
        self.socket.sendto(osc_message(address, *args), (HOST, MAX_LISTENS))

    def receive(self, timeout: float):
        """The next message from Max, or None after `timeout` seconds. Fails if Max exits. The
        harness's log lines (/db/log) are printed when verbose, and returned like any other."""
        deadline = time.monotonic() + timeout
        while time.monotonic() < deadline:
            self._tick()
            if self.process.poll() is not None:
                raise RunError(f"Max exited (status {self.process.returncode}) — see {self.console_path}")
            try:
                data, _ = self.socket.recvfrom(65536)
            except socket.timeout:
                continue
            address, args = parse_osc(data)
            if address == "/db/log" and self.verbose:
                print(f"      log: {' '.join(str(a) for a in args)}")
            return address, args
        return None

    def wait_for(self, address: str, timeout: float, poll=None, every: float = 1.0, text: str = "") -> list:
        """Wait for `address` (with `text` in its first argument, if given), sending `poll` (a
        message) every `every` seconds meanwhile."""
        deadline = time.monotonic() + timeout
        while time.monotonic() < deadline:
            if poll:
                self.send(poll)
            message = self.receive(every)
            if message and message[0] == address and (not text or (message[1] and text in str(message[1][0]))):
                return message[1]
        raise RunError(f"Max did not answer {address} within {timeout:.0f} s — see {self.console_path}")

    def start(self) -> None:
        print(f"  launching Max (console: {self.console_path.relative_to(ROOT)})")
        self.wait_for("/ping/return", 180, poll="/ping", every=2)
        self.db_path = self.wait_for("/testdb/path", 30, poll="/testdb/path?", every=2)[0]
        print("  waiting for Max's file database")
        self.wait_for("/db/ready", 600, poll="/db/ready?", every=2)

    def run_test(self, name: str, timeout: float) -> float:
        """Open one test patcher and wait for it to terminate itself. Returns the seconds taken."""
        started = time.monotonic()
        # the harness logs "preparing to run" as it opens the patcher; the request has been seen to
        # go unanswered right after a crashed session, so it is repeated before giving up
        for _ in range(3):
            self.send(f"test.master run {name}")
            try:
                self.wait_for("/db/log", 15, text="preparing to run")
                break
            except RunError:
                continue
        else:
            raise RunError(f"Max did not start {name} — is a dialog open in Max? (see {self.console_path})")
        self.wait_for("/test/all/complete", timeout)
        return time.monotonic() - started

    def quit(self) -> None:
        if self.process.poll() is None:
            self.send("max quit")
            try:
                self.process.wait(30)
            except subprocess.TimeoutExpired:
                print("  Max did not quit; terminating it")
                self.process.terminate()
                try:
                    self.process.wait(15)
                except subprocess.TimeoutExpired:
                    self.process.kill()
        self.socket.close()
        self.console.close()


# ---- results ----------------------------------------------------------------------------------


def last_test_id(db_path: str) -> int:
    if not db_path or not Path(db_path).exists():
        return 0
    with sqlite3.connect(db_path) as db:
        row = db.execute("SELECT MAX(test_id) FROM tests").fetchone()
    return row[0] or 0


def report(db_path: str, after_id: int, expected: list[str]) -> list[str]:
    """Print each test's assertions recorded after `after_id`; return the failures."""
    failures = []
    with sqlite3.connect(db_path) as db:
        tests = db.execute("SELECT test_id, test_name FROM tests WHERE test_id > ? ORDER BY test_id",
                           (after_id,)).fetchall()
        seen = set()
        for test_id, test_name in tests:
            name = Path(test_name).name
            seen.add(name)
            results: dict[str, bool] = {}
            for assertion, value in db.execute(
                    "SELECT assertion_name, assertion_value FROM assertions WHERE test_id_ext = ? "
                    "ORDER BY assertion_id", (test_id,)):
                results[assertion] = results.get(assertion, True) and value == "Pass"
            failed = [a for a, ok in results.items() if not ok]
            if not results:
                failed = ["(no assertions recorded)"]
            status = "FAIL" if failed else "pass"
            print(f"  {status}  {name}  ({len(results)} assertions)")
            for assertion in failed:
                print(f"          failed: {assertion}")
                failures.append(f"{name}: {assertion}")
            if failed:
                for (text,) in db.execute("SELECT text FROM logs WHERE test_id_ext = ? ORDER BY log_id",
                                          (test_id,)):
                    print(f"          log: {text}")
    for name in expected:
        if name not in seen:
            print(f"  FAIL  {name}  (never ran)")
            failures.append(f"{name}: never ran")
    return failures


def soak_summary(session: MaxSession, after_id: int) -> str:
    """What the soak measured: Max's memory, the reloads, and what the patch logged each minute."""
    lines = []
    if len(session.memory) > 2:
        # from the second sample, a minute in: by then the patcher has made its objects
        start, last = session.memory[1], session.memory[-1]
        peak = max(kb for _, kb in session.memory)
        lines.append(f"Max's memory: {start[1] / 1024:.0f} MB a minute in, {last[1] / 1024:.0f} MB at the end "
                     f"({(last[1] - start[1]) / 1024:+.1f} MB; peak {peak / 1024:.0f} MB)")
        lines.append("  each minute (MB): " + " ".join(f"{kb / 1024:.0f}" for _, kb in session.memory))
    runs = session.console_path.read_text(errors="replace").count("Loaded maxtest_soak.py:")
    lines.append(f"runs of maxtest_soak.py announced in the console: {runs}")
    if session.db_path:
        with sqlite3.connect(session.db_path) as db:
            logged = db.execute("SELECT text FROM logs WHERE test_id_ext > ? ORDER BY log_id", (after_id,)).fetchall()
        series: dict[str, list[str]] = {}
        for (text,) in logged:
            label, _, value = text.partition(" ")
            if label in ("cpu", "executions", "objects"):
                series.setdefault(label, []).append(value)
        for label, values in series.items():
            lines.append(f"{label} (each minute): {' '.join(values)}")
    return "\n".join(lines)


def perf_results(session: MaxSession, after_id: int) -> dict:
    """Average the perf patcher's readings of Max's CPU meter (see make_patchers.perf)."""
    with sqlite3.connect(session.db_path) as db:
        logged = [text for (text,) in db.execute("SELECT text FROM logs WHERE test_id_ext > ? ORDER BY log_id",
                                                 (after_id,))]
    audio: dict[str, float] = {}
    readings: dict[tuple, list[float]] = {}
    for text in logged:
        words = text.split()
        if len(words) == 2 and words[0] in ("rate", "vector", "io"):
            audio.setdefault(words[0], float(words[1]))
        elif len(words) == 4 and words[0] == "cpu":
            readings.setdefault((words[1], int(words[2])), []).append(float(words[3]))
    none = readings.get(("none", 0), [])
    baseline = sum(none) / len(none) if none else 0.0
    loads = []
    for (name, count), values in readings.items():
        if name == "none":
            continue
        mean = sum(values) / len(values)
        loads.append({"class": name, "instances": count, "readings": values, "cpu": mean,
                      "per_instance": (mean - baseline) / count})
    return {"sample_rate": audio.get("rate", 0.0), "vector_size": int(audio.get("vector", 0)),
            "io_vector_size": int(audio.get("io", 0)), "baseline": baseline, "loads": loads}


# ---- setting up and putting things back --------------------------------------------------------


def check_prerequisites(max_app: Path, packages: Path) -> None:
    if sys.platform != "darwin":
        raise RunError("the runtime tests run on macOS only (they launch Max)")
    if not (max_app / "Contents" / "MacOS" / "Max").exists():
        raise RunError(f"no Max at {max_app} (use --max)")
    if subprocess.run(["pgrep", "-x", "Max"], capture_output=True).returncode == 0:
        raise RunError("Max is running — quit it first (the tests launch their own)")
    if not EXTERNAL.exists():
        raise RunError("the external is not built — cmake -S . -B build && cmake --build build")
    if not SUPPORT.exists():
        raise RunError("no runtime in support/ — run scripts/install-runtime.sh")
    if not packages.is_dir():
        raise RunError(f"no Max Packages folder at {packages} (use --packages)")
    ours = packages / "PythonTap"
    if not ours.exists() or ours.resolve() != ROOT:
        raise RunError(f"{ours} is not this checkout — clone the repo there or symlink it in "
                       f"(ln -s {ROOT} {ours})")
    others = [p for p in packages.glob("*/externals/tap.python~.mxo") if p.resolve().parents[1] != ROOT]
    if others:
        raise RunError(f"another tap.python~ is installed, which Max could load instead: {others[0]}")
    if not (HARNESS / "source").is_dir():
        raise RunError("the max-test submodule is missing — git submodule update --init --recursive")


def build_oscar() -> None:
    if OSCAR.exists():
        return
    print("  building the max-test harness's oscar extension")
    build = HARNESS / "build"
    for command in (["cmake", "-S", str(HARNESS), "-B", str(build), "-DCMAKE_BUILD_TYPE=Release"],
                    ["cmake", "--build", str(build), "--config", "Release"]):
        if subprocess.run(command, capture_output=True).returncode != 0:
            raise RunError(f"building the harness failed: {' '.join(command)}")


def install_harness(packages: Path) -> None:
    """Install the pinned harness into Packages as max-test: a real folder, because Max loads a
    package's extensions (oscar is one) only from a real folder, never through a symlink. Only a
    max-test this script installed (it carries the stamp file) is ever replaced; the results
    database in it is kept."""
    installed = packages / "max-test"
    if installed.is_symlink():
        installed.unlink()
    elif installed.exists() and not (installed / HARNESS_STAMP).exists():
        raise RunError(f"{installed} is another copy of max-test — remove it (or move it out of Packages); "
                       "run.py installs the version pinned in runtime-tests/max-test")
    installed.mkdir(exist_ok=True)
    for folder in ("extensions", "misc", "patchers"):
        shutil.rmtree(installed / folder, ignore_errors=True)
        shutil.copytree(HARNESS / folder, installed / folder, symlinks=True)
    shutil.copyfile(TESTS / "max-test-config.json", installed / "misc" / "max-test-config.json")
    (installed / HARNESS_STAMP).write_text(
        f"Installed by {Path(__file__).relative_to(ROOT)} in {ROOT} from its runtime-tests/max-test\n"
        "submodule; run.py replaces it on every run. Delete this folder to uninstall.\n")


def link_test_package(packages: Path) -> Path | None:
    """Link runtime-tests/ into Packages, so Max finds the test patchers by name. Returns the
    link if this call made it."""
    link = packages / TEST_PACKAGE
    if link.is_symlink() or link.exists():
        if link.resolve() != TESTS:
            raise RunError(f"{link} already exists and is not {TESTS} — move it aside for the run")
        return None
    link.symlink_to(TESTS)
    return link


def copy_fixtures() -> list[Path]:
    copied = []
    for fixture in sorted(FIXTURES.glob("maxtest_*.py")):
        destination = SCRIPTS_DIR / fixture.name
        shutil.copyfile(fixture, destination)
        copied.append(destination)
    return copied


def restore_support() -> None:
    if SUPPORT_ASIDE.exists():
        if SUPPORT.exists():
            raise RunError(f"both {SUPPORT.name}/ and {SUPPORT_ASIDE.name}/ exist — keep one")
        SUPPORT_ASIDE.rename(SUPPORT)


# ---- the sessions -----------------------------------------------------------------------------


def run_session(max_app: Path, name: str, steps: list, verbose: bool, timeout: float) -> list[str]:
    """Run `steps` — test patcher names, or callables to run between them — in one Max."""
    print(f"\n== session: {name}")
    session = MaxSession(max_app, name, verbose)
    expected = [s for s in steps if isinstance(s, str)]
    first_id = 0
    try:
        session.start()
        first_id = last_test_id(session.db_path)
        session.sample_memory = name == "soak"  # from here: the soak patcher opens next
        for step in steps:
            if callable(step):
                step()
                continue
            print(f"  running {step}")
            seconds = session.run_test(step, timeout)
            if verbose:
                print(f"      done in {seconds:.1f} s")
    except RunError as error:
        print(f"  ERROR: {error}")
        session.quit()
        failures = report(session.db_path, first_id, expected) if session.db_path else []
        failures.append(f"{name}: {error}")
    else:
        session.quit()
        failures = report(session.db_path, first_id, expected)
    if name == "soak":
        summary = soak_summary(session, first_id)
        (LOGS / "soak.summary").write_text(summary + "\n")
        print("\n" + summary)
    if name == "perf" and session.db_path:
        results = perf_results(session, first_id)
        (LOGS / "perf.json").write_text(json.dumps(results, indent=2) + "\n")
        print(f"\nMax's DSP CPU, the device at {results['sample_rate']:g} Hz (no object: {results['baseline']:.1f}%):")
        for load in results["loads"]:
            print(f"  {load['instances']:>3} x {load['class']:<11} {load['cpu']:5.1f}%  ({load['per_instance']:.2f}% each)")
    return failures


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--max", type=Path, default=Path("/Applications/Max.app"), help="the Max application")
    parser.add_argument("--packages", type=Path, default=Path.home() / "Documents" / "Max 9" / "Packages",
                        help="Max's Packages folder")
    parser.add_argument("--session", choices=["all", "main", "without-runtime", "soak", "perf"], default="all",
                        help="all: without-runtime then main; soak and perf run only when asked for")
    parser.add_argument("--only", action="append", default=[],
                        help="run only the main tests whose file names contain this (repeatable)")
    parser.add_argument("--timeout", type=float, default=180, help="seconds allowed per test patcher")
    parser.add_argument("--soak-timeout", type=float, default=120, help="minutes allowed for the soak")
    parser.add_argument("--keep-link", action="store_true",
                        help=f"leave runtime-tests/ linked into Packages (as {TEST_PACKAGE}) afterwards")
    parser.add_argument("-v", "--verbose", action="store_true", help="print the harness's log as it runs")
    args = parser.parse_args()

    main_tests = sorted(p.name for p in PATCHERS.glob("*.maxtest.maxpat"))
    if args.only:
        main_tests = [t for t in main_tests if any(o in t for o in args.only)]

    link: Path | None = None
    fixtures: list[Path] = []
    failures: list[str] = []
    try:
        restore_support()  # a previous run that was killed may have left it aside
        check_prerequisites(args.max, args.packages)
        build_oscar()
        install_harness(args.packages)
        link = link_test_package(args.packages)
        fixtures = copy_fixtures()

        if args.session in ("all", "without-runtime"):
            SUPPORT.rename(SUPPORT_ASIDE)
            try:
                failures += run_session(args.max, "without-runtime",
                                        [WITHOUT_RUNTIME[0], restore_support, WITHOUT_RUNTIME[1]],
                                        args.verbose, args.timeout)
            finally:
                restore_support()
        if args.session in ("all", "main"):
            if not main_tests:
                raise RunError("no test patchers match")
            failures += run_session(args.max, "main", main_tests, args.verbose, args.timeout)
        if args.session == "soak":
            failures += run_session(args.max, "soak", [SOAK], args.verbose, args.soak_timeout * 60)
        if args.session == "perf":
            failures += run_session(args.max, "perf", [PERF], args.verbose, 600)
    except RunError as error:
        print(f"error: {error}", file=sys.stderr)
        return 2
    except KeyboardInterrupt:
        print("interrupted", file=sys.stderr)
        return 130
    finally:
        try:
            restore_support()
        except RunError as error:
            print(f"error: {error}", file=sys.stderr)
        for fixture in fixtures:
            fixture.unlink(missing_ok=True)
        if link and not args.keep_link:
            link.unlink(missing_ok=True)

    print()
    if failures:
        print(f"{len(failures)} failure(s):")
        for failure in failures:
            print(f"  {failure}")
        return 1
    print("all runtime tests passed")
    return 0


if __name__ == "__main__":
    sys.exit(main())
