#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
# Copyright 2022-2026 Timothy Place.
"""Measure what process() costs, and a tap.python message, and write them into ReadMe.md (plan 6.3, 9.1).

    python3 scripts/update-perf-docs.py              # build core/bench (Release), run it, update ReadMe.md
    python3 scripts/update-perf-docs.py --max        # also measure in Max (macOS; quit Max first)
    python3 scripts/update-perf-docs.py --check      # print the tables without writing them

Builds the benchmark against the runtime in support/ (or --python), runs it, and replaces the text
between the perf markers in ReadMe.md with the measurements and the machine they were taken on.
With --max it also runs `runtime-tests/run.py --session perf` — Max's own DSP CPU meter with
instances of the examples — and replaces the text between the perf-max markers. Never edit those
tables by hand: rerun this on an otherwise idle machine, and commit the result.
"""

from __future__ import annotations

import argparse
import datetime
import json
import os
import platform
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
README = ROOT / "ReadMe.md"
BUILD = ROOT / "build-bench"
BEGIN = "<!-- perf:begin (generated by scripts/update-perf-docs.py; do not edit) -->"
END = "<!-- perf:end -->"
MAX_BEGIN = "<!-- perf-max:begin (generated by scripts/update-perf-docs.py --max; do not edit) -->"
MAX_END = "<!-- perf-max:end -->"
PERF_JSON = ROOT / "runtime-tests" / "logs" / "perf.json"
BUSY = 1.5  # a load average above this makes the measurements suspect
LOAD_AVERAGE = 0.0  # when measuring, for the record


def run(command: list[str], **kwargs) -> str:
    result = subprocess.run(command, capture_output=True, text=True, **kwargs)
    if result.returncode != 0:
        sys.exit(f"error: {' '.join(command)} failed:\n{result.stdout}{result.stderr}")
    return result.stdout


def default_python() -> Path:
    for candidate in (ROOT / "support" / "bin" / "python3", ROOT / "support" / "python.exe"):
        if candidate.exists():
            return candidate
    sys.exit("error: no runtime in support/ — run scripts/install-runtime, or pass --python")


def cpu_name() -> str:
    if sys.platform == "darwin":
        return run(["sysctl", "-n", "machdep.cpu.brand_string"]).strip()
    if sys.platform.startswith("linux"):
        for line in Path("/proc/cpuinfo").read_text().splitlines():
            if line.startswith("model name"):
                return line.split(":", 1)[1].strip()
    return platform.processor() or platform.machine()


def os_name() -> str:
    if sys.platform == "darwin":
        return f"macOS {platform.mac_ver()[0]} ({platform.machine()})"
    return f"{platform.system()} {platform.release()} ({platform.machine()})"


def percent(load: float) -> str:
    value = load * 100.0
    return f"{value:.2g}%" if value < 10 else f"{value:.0f}%"


def cost(measurement: dict) -> str:
    rate, vector_size, load = measurement["sample_rate"], measurement["vector_size"], measurement["load"]
    if measurement["block"]:
        return f"{load / rate * vector_size * 1e6:.2g} µs per vector"
    nanoseconds = load / rate * 1e9
    return f"{nanoseconds / 1000:.2g} µs per sample" if nanoseconds >= 1000 else f"{nanoseconds:.2g} ns per sample"


def machine(python: Path) -> str:
    numpy_version = run([str(python), "-c", "import numpy; print(numpy.__version__)"]).strip()
    python_version = run([str(python), "-c", "import platform; print(platform.python_version())"]).strip()
    return f"{cpu_name()}, {os_name()}, CPython {python_version}, numpy {numpy_version}"


def max_table(results: dict, python: Path, bench: dict) -> str:
    rate, vector_size = results["sample_rate"], results["vector_size"]
    described = {"default": ("`default.py`, per sample", "default", vector_size),
                 "numpy_gain": (f"`numpy_gain.py`, per vector of {vector_size}", "numpy_gain", vector_size),
                 "allpass": ("`allpass.py`, per sample", "allpass", vector_size),
                 "numpy_allpass": (f"`numpy_allpass.py`, per vector of {vector_size}", "numpy_allpass", vector_size)}
    predicted = {(m["subject"], m["sample_rate"], m["vector_size"]): m["load"] for m in bench["measurements"]}
    lines = [MAX_BEGIN, "",
             f"| In Max at {rate / 1000:g} kHz | Instances | Max's CPU meter | Each | `core/bench`, each |",
             "|---|---:|---:|---:|---:|"]
    for load in results["loads"]:
        label, subject, size = described.get(load["class"], (load["class"], load["class"], vector_size))
        # measured at this rate, or else scaled from 48 kHz: per sample, and per vector at a given
        # vector size, the cost is proportional to the sample rate
        bench_load = predicted.get((subject, rate, size))
        if bench_load is None and (subject, 48000.0, size) in predicted:
            bench_load = predicted[(subject, 48000.0, size)] * rate / 48000.0
        lines.append(f"| {label} | {load['instances']} | {load['cpu']:.0f}% | "
                     f"{percent(load['per_instance'] / 100)} | {percent(bench_load) if bench_load else '—'} |")
    lines += [
        "",
        f"Max's own DSP CPU meter (`adstatus cpu`): the mean of ten readings a second apart with the instances "
        f"running in a `poly~`, less the reading with no object ({results['baseline']:.1f}%); *each* divides by "
        f"the number running. The audio device ran at {rate / 1000:g} kHz with {vector_size}-sample signal "
        f"vectors and a {results['io_vector_size']}-sample I/O vector. The meter reads in whole percent. "
        f"Measured {datetime.date.today():%Y-%m-%d} with Max {max_version()}, on {machine(python)}.",
        "",
        MAX_END,
    ]
    return "\n".join(lines)


def max_version() -> str:
    plist = Path("/Applications/Max.app/Contents/Info.plist")
    if not plist.exists():
        return "(version unknown)"
    return run(["defaults", "read", str(plist.with_suffix("")), "CFBundleShortVersionString"]).split()[0]


def spread(results: dict) -> float:
    return max(m["median"] / m["load"] - 1.0 for m in results["measurements"])


def comparison(results: dict) -> list[str]:
    """A sentence comparing allpass.py with numpy_allpass.py, from the measurements."""
    load = {(m["subject"], m["sample_rate"], m["vector_size"]): m["load"] for m in results["measurements"]}
    try:
        pairs = [(rate, load[("allpass", rate, 64)], load[("numpy_allpass", rate, 64)]) for rate in (48000.0, 96000.0)]
    except KeyError:
        return []
    ratios = " and ".join(f"{per_sample / per_vector:.0f}× less at {rate / 1000:g} kHz ({percent(per_vector)} of a core "
                          f"against {percent(per_sample)})" for rate, per_sample, per_vector in pairs)
    return ["", "`numpy_allpass.py` computes exactly what `allpass.py` does — the core battery checks it sample for "
            f"sample — and in 64-sample vectors needs {ratios}. It computes a vector in stretches no longer than "
            "the delay, one numpy expression each: the default 1 ms delay is 48 samples at 48 kHz, so a 64-sample "
            "vector takes two, and 96 at 96 kHz, so it takes one — a delay shorter than the vector costs more."]


def messages(results: dict) -> list[str]:
    """A sentence on what a tap.python message costs, from the measurements (plan 9.1)."""
    calls = {c["subject"]: c for c in results.get("calls", [])}
    if "bench_list_identity" not in calls or "scale" not in calls:
        return []
    atoms = calls["bench_list_identity"]["atoms"]

    def microseconds(subject: str) -> str:
        return f"{calls[subject]['seconds'] * 1e6:.2g} µs"

    return ["", f"A message to `tap.python` with a list of {atoms} numbers, each converted in and the list the "
            f"method returns converted back out — called as Max's main or scheduler thread calls it, never the "
            f"audio thread — costs {microseconds('bench_list_identity')} when the class returns the list as it "
            f"came (the bridge alone), and {microseconds('scale')} for `scale.py`, which takes it as one numpy "
            f"array."]


def table(results: dict, python: Path) -> str:
    rows: dict[tuple, dict] = {}
    for m in results["measurements"]:
        rows.setdefault((m["subject"], m["vector_size"]), {"first": m})[m["sample_rate"]] = m
    lines = [
        BEGIN,
        "",
        "| `process()` | Cost (at 48 kHz) | CPU at 48 kHz | CPU at 96 kHz |",
        "|---|---|---:|---:|",
    ]
    for (subject, vector_size), row in rows.items():
        first = row["first"]
        description = re.sub(r"(\w+\.py)", r"`\1`", first["description"].partition(": ")[2])
        form = f"per sample, vectors of {vector_size}" if not first["block"] else f"per vector of {vector_size}"
        lines.append(f"| {description} — {form} | {cost(row[48000.0])} | {percent(row[48000.0]['load'])} | "
                     f"{percent(row[96000.0]['load'])} |")
    lines += comparison(results)
    lines += messages(results)
    lines += [
        "",
        f"The share of one core: each row timed once per round for seven rounds, interleaved, keeping its "
        f"fastest; every median was within {spread(results):.0%} of it. Measured "
        f"{datetime.date.today():%Y-%m-%d} on {machine(python)}, load average {LOAD_AVERAGE:.1f}.",
        "",
        END,
    ]
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--python", type=Path, help="the CPython 3.13 to build against (default: support/)")
    parser.add_argument("--check", action="store_true", help="print the tables instead of writing ReadMe.md")
    parser.add_argument("--max", action="store_true", help="also measure in Max (runtime-tests/run.py)")
    args = parser.parse_args()
    python = args.python or default_python()
    global LOAD_AVERAGE
    LOAD_AVERAGE = os.getloadavg()[0] if hasattr(os, "getloadavg") else 0.0
    if LOAD_AVERAGE > BUSY:
        print(f"warning: the load average is {LOAD_AVERAGE:.1f} — other work will inflate the numbers; "
              "measure on an idle machine", file=sys.stderr)

    print("building core/bench (Release)")
    run(["cmake", "-S", str(ROOT / "core"), "-B", str(BUILD), "-DCMAKE_BUILD_TYPE=Release",
         f"-DPython3_EXECUTABLE={python}"])
    run(["cmake", "--build", str(BUILD), "--config", "Release", "--target", "tap_python_bench"])
    candidates = [BUILD / "bench" / "tap_python_bench", BUILD / "bench" / "Release" / "tap_python_bench.exe"]
    bench = next((c for c in candidates if c.exists()), None)
    if not bench:
        sys.exit("error: the benchmark did not build")

    print("measuring (about a minute)")
    output = BUILD / "bench" / "results.json"
    print(run([str(bench), "--json", str(output)]), end="")
    bench = json.loads(output.read_text())
    blocks = {(BEGIN, END): table(bench, python)}

    if args.max:
        print("measuring in Max (runtime-tests/run.py --session perf, about four minutes)")
        result = subprocess.run([sys.executable, str(ROOT / "runtime-tests" / "run.py"), "--session", "perf"])
        if result.returncode != 0:
            sys.exit("error: the Max measurement failed")
        blocks[(MAX_BEGIN, MAX_END)] = max_table(json.loads(PERF_JSON.read_text()), python, bench)

    if args.check:
        print("\n\n".join(blocks.values()))
        return 0
    readme = README.read_text()
    for (begin, end), text in blocks.items():
        if begin not in readme or end not in readme:
            sys.exit(f"error: {README.name} has no {begin} … {end} markers")
        start, stop = readme.index(begin), readme.index(end) + len(end)
        readme = readme[:start] + text + readme[stop:]
    README.write_text(readme)
    print(f"updated {README.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
