#!/usr/bin/env python3
# Copyright 2022-2026 Timothy Place. All rights reserved.
# Use of this source code is governed by the MIT License found in the License.md file.
"""Regenerate the pinned-dependency locks the runtime installers verify against.

    scripts/runtime.lock       the python-build-standalone CPython archives for each platform
                               we ship, by exact asset name and SHA256
    scripts/requirements.lock  the Python packages installed into the runtime (attrs, numpy),
                               with the SHA256 of every wheel for the pinned CPython series

The installers (scripts/install-runtime.sh / .ps1) and CI only ever install what these files
name, with the hashes they record, so a replaced release asset or a new upload to PyPI cannot
change what gets installed. Upgrading is a deliberate act (D4 in docs/PRODUCTION-PLAN.md):
run this with the new pins, review the diff, and commit it.

    python3 scripts/update-locks.py                                    # refresh the current pins
    python3 scripts/update-locks.py --release 20260623 --numpy 2.5.3   # move a pin

The hashes are the ones the upstream publishes at the time this runs (python-build-standalone's
SHA256SUMS, PyPI's JSON API) — pinning them in the repo is what makes later installs match it.
"""

import argparse
import json
import re
import sys
import urllib.request
from pathlib import Path

SCRIPTS = Path(__file__).resolve().parent

PBS_URL = "https://github.com/astral-sh/python-build-standalone/releases/download/{release}/SHA256SUMS"
PYPI_URL = "https://pypi.org/pypi/{name}/{version}/json"

# The platforms the runtime is installed on: the shipping targets, plus Linux for CI and
# development (the core battery and the Max-glue test embed a CPython there).
RUNTIME_TRIPLES = ["aarch64-apple-darwin", "x86_64-apple-darwin", "x86_64-pc-windows-msvc"]
WHEEL_PLATFORMS = re.compile(r"(macosx_[0-9_]+_(arm64|x86_64)|win_amd64|manylinux_[0-9_]+_(x86_64|aarch64))\.whl$")

DEFAULTS = {"release": "20260623", "series": "3.13", "attrs": "26.1.0", "numpy": "2.5.3"}


def fetch(url):
    with urllib.request.urlopen(url, timeout=60) as response:
        return response.read().decode()


def runtime_lock(release, series):
    sums = fetch(PBS_URL.format(release=release))
    pattern = re.compile(
        rf"^([0-9a-f]{{64}})\s+(cpython-{re.escape(series)}\.[0-9]+\+{release}-(\S+)-install_only\.tar\.gz)$"
    )
    found = {}
    for line in sums.splitlines():
        match = pattern.match(line.strip())
        if match and match.group(3) in RUNTIME_TRIPLES:
            found[match.group(3)] = (match.group(2), match.group(1))
    missing = [t for t in RUNTIME_TRIPLES if t not in found]
    if missing:
        sys.exit(f"error: release {release} has no cpython {series} install_only asset for {', '.join(missing)}")

    lines = [
        "# Generated by scripts/update-locks.py — do not edit by hand.",
        f"# CPython {series} from python-build-standalone release {release}:",
        "# <target triple> <asset> <sha256>",
        f"release {release}",
    ]
    lines += [f"{t} {found[t][0]} {found[t][1]}" for t in RUNTIME_TRIPLES]
    return "\n".join(lines) + "\n"


def requirement(name, version, series):
    data = json.loads(fetch(PYPI_URL.format(name=name, version=version)))
    tag = "cp" + series.replace(".", "")
    hashes = []
    for f in data["urls"]:
        filename = f["filename"]
        if f["packagetype"] != "bdist_wheel":
            continue
        pure = filename.endswith("-py3-none-any.whl")
        native = f"-{tag}-{tag}-" in filename and WHEEL_PLATFORMS.search(filename)
        if pure or native:
            hashes.append((filename, f["digests"]["sha256"]))
    if not hashes:
        sys.exit(f"error: {name} {version} has no wheel for CPython {series} on the pinned platforms")

    # pip's requirements format allows no comment inside a continued requirement, so the wheel
    # names go in a comment above it
    hashes.sort()
    lines = [f"# {name} {version}: " + ", ".join(filename for filename, _ in hashes)]
    lines.append(f"{name}=={version} \\")
    lines += [
        f"    --hash=sha256:{digest}" + (" \\" if i < len(hashes) - 1 else "") for i, (_, digest) in enumerate(hashes)
    ]
    return "\n".join(lines)


def requirements_lock(pins, series):
    header = [
        "# Generated by scripts/update-locks.py — do not edit by hand.",
        f"# The packages installed into the embedded CPython {series} runtime, wheels only,",
        "# installed with: pip install --require-hashes --only-binary :all: -r requirements.lock",
    ]
    return "\n".join(header + [requirement(n, v, series) for n, v in pins]) + "\n"


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    for key, value in DEFAULTS.items():
        parser.add_argument(f"--{key}", default=value, help=f"(default: {value})")
    args = parser.parse_args()

    (SCRIPTS / "runtime.lock").write_text(runtime_lock(args.release, args.series))
    pins = [("attrs", args.attrs), ("numpy", args.numpy)]
    (SCRIPTS / "requirements.lock").write_text(requirements_lock(pins, args.series))
    print(f"wrote {SCRIPTS / 'runtime.lock'} and {SCRIPTS / 'requirements.lock'}")


if __name__ == "__main__":
    main()
